
name: rails-stack-template
description: This is a stack for deploying a Rails Apps + MYSQL DB to Azu
branding:
  icon: 'Azure.svg'
  color: 'blue'
inputs:
 - name: Reviewer_Count
   default: 2
   description: Number of required reviewers for PR
   validvalues: 
   - 2
   - 3
   - 4
   - 5
   - 6
 - name: DEV_SPN_ID
   description: SPN ID for Dev deployments
   is_secret: true
 - name: SQL_Connection_String
   description: SQL_Connection_String for Dev deployments
   is_secret: true
 - name: PROD_SPN_ID
   description: PROD_SPN_ID for Dev deployments
   is_secret: true
#-------------------------------------------------------------

configs:
# Meta data for creating the new repository
- repo-metadata:
    parameters:
      description: This is a Azure GitHub Action
      secrets:
      - name: DEV_SPN_ID
        value: ${{ inputs.DEV_SPN_ID }}
      topics:
      - azure
      - action

 # Branch protection rules
- branches:
   - name: releases/*
     parameters:
       dismiss-stale-reviews: true
       require-code-owner-reviews: true
       required-approving-review-count: ${{ inputs.Reviewer_Count }}
   
   - name: main
     parameters:
       dismiss-stale-reviews: true
       require-code-owner-reviews: true
       required-approving-review-count: ${{ inputs.Reviewer_Count }}
- environments: 
  - name: staging
    parameters: 
      protected-branches: false
      secrets:
        - name: SQL_Connection_String
          value: ${{ inputs.SQL_Connection_String }}
        - name: PROD_SPN_ID
          value: ${{ inputs.PROD_SPN_ID }}
            
- security:
    parameters: 
      vulnerability-alerts: true
      automated-security-fixes: true
